# -*- coding: utf-8 -*-
"""imlproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Fy9l-hkTOOkmLE2bhQioX2USbaFLm-F
"""

import pandas as pd
from google.colab import files
df=pd.read_csv("/content/sample_data/archive.zip")

df

x=df[["Age"]]
y=df["Blood_Pressure_Abnormality"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=11)
# print(x_train)
# print(x_test)
# print(y_test)
# print(y_train)

from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=11,leaf_size=20,metric="euclidean")
clf.fit(x_train,y_train)

print(clf.score(x_test,y_test))

print(clf.predict(x_test))
prediction=clf.predict(x_test)
print(y_test)

from sklearn.metrics import recall_score
re=recall_score(y_test,prediction)
re

diff=prediction-y_test
print(diff)
print(sum(abs(diff)))

from sklearn.metrics import recall_score
re=recall_score(y_test,prediction)
re

from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,prediction)
print(cm)

from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

f1=f1_score(y_test,prediction)
f1

pr=precision_score(y_test,prediction)
pr